### ISSUE TITLE
Arquitetura Kubernetes

### ISSUE THREAD

**Issue by vitorrafael** [FIAP-8SOAT-G6/tech-challenge-lanchonete#47]
Criar arquitetura em K8s que atenda os seguintes requisitos:
1. Requisitos Funcionais.
2. Escalabilidade com aumento/diminuição de Pods conforme demanda.

**Comment by anadezuo** [comment]
TC
Item 2 > Criar uma arquitetura em Kubernetes que atenda os seguintes requisitos:
a. Os requisitos funcionais descritos nos itens anteriores (item problema).
b. Escalabilidade com aumento e diminuição de Pods conforme demanda.
c. Os arquivos manifestos (yaml) precisam estar no Github junto com a nova versão do código.
