### ISSUE TITLE
Diagramas de Arquitetura

### ISSUE THREAD

**Issue by vitorrafael** [FIAP-8SOAT-G6/tech-challenge-lanchonete#49]
Contemplar:
* Requisitos de Negócio
* Requisitos de Infraestrutura (MiniKube, Docker Kubernetes, AKS, EKS, GKE, etc)

**Comment by anadezuo** [comment]
Alguns comentários que ajudam na descrição

[Dúvida](https://discord.com/channels/1065992165232214066/1280132960586305577/1280295660012175441)

É o desenho de arquitetura, não temos um modelo, basta detalhar os fluxos e serviços da cloud utilizada, trazendo os requisitos de negócio.. por exemplo:

Requisitos de infra:

Desenho que contém o que foi utilizado, como Kubernetes, Banco de dados, e a comunicação entre si.

Requisitos de negócio:

Ainda no desenho de infra, detalhar melhor, como por exemplo:

O restaurante está sofrendo com quedas constantes no totem onde os clientes fazem o pedido, então o restaurante optou por aumentar seus recursos com autoscaling.

Baseado nesse requisito de negócio (problema), o desenho deve conter o desenho do HPA indicando como o autoscaling vai funcionar na aplicação que está sofrendo com quedas.

Perceba que o desenho infra detalha todos serviços e comunicação utilizados, e o desenho de negócio complementa o desenho de infra trazendo mais riqueza aos detalhes mostrando que o requisitos de negócio (melhorar a disponibilidade, segurança, escalabilidade, etc) foram aplicados no fluxo.
