### ISSUE TITLE
Implementar CRUD dos Produtos

### ISSUE THREAD

**Issue by vitorrafael** [FIAP-8SOAT-G6/tech-challenge-lanchonete#5]
Não está incluído no fluxo do Event Storming, mas precisamos gerenciar os produtos de alguma forma conforme a descrição do Tech Challenge (ver `b - iii`).

![Image](https://github.com/user-attachments/assets/fccfe8c2-265f-4660-83e4-a37fa21fa755)

**Comment by anadezuo** [comment]
Issue já implementada
