### ISSUE TITLE
Implementar Fake Checkout

### ISSUE THREAD

**Issue by vitorrafael** [FIAP-8SOAT-G6/tech-challenge-lanchonete#8]

**Comment by RobsonArcoleze** [comment]
Ao pesquisar sobre o assunto e consultar o fórum, chegou-se a conclusão que não precisa implementar um endpoint para fake checkout, o pedido já deve ser salvo com o status de pago nesta primeira fase, na segunda fase será feito a integração com o meio de pagamento.
